# Generated by Django 3.2.4 on 2021-07-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customerDetails',
            new_name='customerDetail',
        ),
        migrations.RenameModel(
            old_name='transferDetails',
            new_name='transferDetail',
        ),
    ]
